### ISSUE TITLE
NFS server does not work for Ultra96 V1, PYNQ V2.5

### ISSUE THREAD

**Issue by yahoo2016** [Avnet/Ultra96-PYNQ#54]
I flashed latest PYNQ and ran:
apt update
apt install nfs-kernel-server
I got:
pynq systemd[1]:nfs-server.service: Dependency failed for NFS server and service
pynq systemd[1]:nfs-server.service: Job nfs-server-service/start failed with result "dependency"
I tried systemctl restart nfs-kernel-server and got the same errors.
I tried:
apt purge nfs-kernel-server
apt upgrade
apt install nfs-kernel-server
and got the same errors.

**Comment by zedhed** [comment]
It looks like this is an issue with the runtime of PYNQ, rather than an issue building PYNQ from our GitHub, and you are working on getting NFS working which is not something we can support from here.

I suggest you post this issue on the PYNQ forum and see if there are any suggested remedies there:

https://discuss.pynq.io/

-Kevin
