### ISSUE TITLE
2.6 First Boot up issues(Connection refused, no jypter notebook)

### ISSUE THREAD

**Issue by JackBonnellDevelopment** [Avnet/Ultra96-PYNQ#78]
Hi when i go to the root IP address with a fresh install of pynq 2.6 I can't access through ssh as i get connection refused and i cannot seem to see the "jupyter notebooks" as the default "Apache2 Ubuntu Default Page"

**Comment by focalplane** [comment]
Hi,  Not sure what the issue is with your setup.  No one else has reported this.  Are you attempting to ssh across the usb connection or are you using a usb to ethernet device or wifi?  If wifi, I have never tried to ssh through that.  If wifi is not working then some network settings/scripts can likely be changed to allow it to work.  If using usb then it might be a setting or issue on your host PC.  If usb to ethernet adapter, that would be something totally new to me that is what I use the most, especially since it gives the Ultra96 board network/internet access as well.  There is btw a USB serial terminal as well.
